# Generated by Django 5.2.17 on 2026-09-06 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=30, unique=True, verbose_name='كود الصنف')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الصنف / الأدوات')),
                ('category', models.CharField(choices=[('cups', 'كؤوس استخدام واحد'), ('blades', 'مستلزمات معقمة (شفرات)'), ('oils', 'زيوت ومطهرات'), ('general', 'مستلزمات عامة')], max_length=20, verbose_name='الفئة')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المتاحة')),
                ('min_quantity_warning', models.PositiveIntegerField(default=20, verbose_name='حد التنبيه عند النقص')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='سعر التكلفة للوحدة')),
            ],
            options={
                'verbose_name': 'صنف مخزون',
                'verbose_name_plural': 'المخزون والمستلزمات',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='اسم المريض بالكامل')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='رقم الهاتف')),
                ('gender', models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('chronic_diseases', models.TextField(blank=True, null=True, verbose_name='الأمراض المزمنة / التنبيهات الطبية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'السجل الطبي - المرضى',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='تاريخ الموعد')),
                ('appointment_time', models.TimeField(verbose_name='وقت الموعد')),
                ('cupping_type', models.CharField(choices=[('preventive', 'حجامة وقائية'), ('therapeutic', 'حجامة علاجية'), ('dry', 'حجامة جافة'), ('massage', 'حجامة متزحلقة')], default='preventive', max_length=20, verbose_name='نوع الحجامة')),
                ('status', models.CharField(choices=[('waiting', 'في الانتظار'), ('in_session', 'في العيادة'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='waiting', max_length=15, verbose_name='حالة الحجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الطبيب المعالج')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cuupping.patient', verbose_name='المريض')),
            ],
            options={
                'verbose_name': 'موعد',
                'verbose_name_plural': 'جدول المواعيد والحجوزات',
            },
        ),
        migrations.CreateModel(
            name='CuppingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp_before', models.CharField(max_length=20, verbose_name='ضغط الدم (قبل الجلسة)')),
                ('bp_after', models.CharField(blank=True, max_length=20, null=True, verbose_name='ضغط الدم (بعد الجلسة)')),
                ('blood_sugar', models.CharField(blank=True, max_length=20, null=True, verbose_name='مستوى السكر في الدم')),
                ('cupping_points', models.CharField(help_text='مثال: C7, T1-T2, L4-L5', max_length=255, verbose_name='مواضع الحجامة')),
                ('cups_used_count', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الكؤوس المستخدمة')),
                ('oil_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الزيت المستخدم')),
                ('doctor_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات وتوصيات الطبيب')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ إتمام الجلسة')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='cuupping.appointment', verbose_name='الموعد المرتبط')),
            ],
            options={
                'verbose_name': 'جلسة حجامة',
                'verbose_name_plural': 'سجلات الجلسات الطبية',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ الإجمالي (ر.س)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً (كاش)'), ('card', 'شبكة (مدى/فيزا)'), ('paypal', 'باي بال / دفع إلكتروني')], default='card', max_length=15, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('paid', 'مدفوعة'), ('pending', 'قيد الانتظار'), ('cancelled', 'ملغية')], default='paid', max_length=15, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='cuupping.appointment', verbose_name='الموعد المرتبط')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'المالية والفواتير',
            },
        ),
    ]
